Presentation/Controllers/TopicController.cs
using ApplicationCore.Helpers;
using ApplicationCore.Interfaces;
using ApplicationCore.ViewModels.Topic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {
        private readonly ITopicViewModelService topicViewModelService;
        private readonly ITopicService topicService;
        private readonly ICommonService commonService;
        private readonly IBookmarkService bookmarkService;
        private readonly INotificationRepository notificationRepository;

        public TopicController(ITopicViewModelService topicViewModelService,
                               ITopicService topicService,
                               ICommonService commonService,
                               IBookmarkService bookmarkService,
                               INotificationRepository notificationRepository)
        {
            this.topicViewModelService = topicViewModelService;
            this.topicService = topicService;
            this.commonService = commonService;
            this.bookmarkService = bookmarkService;
            this.notificationRepository = notificationRepository;
        }

        [HttpGet("create-new-topic")]
        public async Task<IActionResult> CreateNewTopic()
        {
            TopicCreateViewModel viewModel = await topicViewModelService.GetCreateViewModelAsync();
            return View(viewModel);
        }

        [HttpPost("create-new-topic")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNewTopic(TopicCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await topicService.CreateNewTopicAsync(viewModel);

                if (result.Succeeded)
                {
                    return RedirectToAction("ReadTopic", new { Id = result.Messages[0] });
                }
                ModelState.AddModelError("", result.Messages[0]);
            }
            return View(viewModel);
        }

        [AllowAnonymous]
        [HttpGet("topic/{id?}")]
        public async Task<IActionResult> ReadTopic(int? id)
        {
            if (id == null)
            {
                return View("PageNotFound");
            }
            TopicViewModel viewModel = await topicViewModelService.GetTopicViewModelAsync(id.Value);

            if (viewModel == null)
            {
                return View("PageNotFound");
            }
            await topicService.IncreaseTopicViewCountAsync(id.Value);
            return View(viewModel);
        }

        [HttpPost("post-topic-reply")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostReplyToTopic(TopicViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await topicService.ReplyToTopicAsync(viewModel.TopicReplyViewModel);

                if (result.Succeeded)
                {
                    return RedirectToAction("ReadTopic", new { Id = result.Messages[0]  });
                }
                ModelState.AddModelError("", result.Messages[0]);
            }
            return RedirectToAction("ReadTopic", new { Id = viewModel.TopicReplyViewModel.TopicId });
        }

        [HttpPost("post-comment-reply")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostReplyToComment(TopicViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await topicService.ReplyToCommentAsync(viewModel.TopicReplyViewModel);

                if (result.Succeeded)
                {
                    return RedirectToAction("ReadTopic", new { Id = result.Messages[0] });
                }
                ModelState.AddModelError("", result.Messages[0]);
            }
            return RedirectToAction("ReadTopic", new { Id = viewModel.TopicReplyViewModel.TopicId });
        }

        [HttpPost("delete-reply")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReply(TopicViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await topicService.DeleteReplyAsync(viewModel.TopicDeleteViewModel);

                if (result.Succeeded)
                {
                    return RedirectToAction("ReadTopic", new { Id = result.Messages[0] });
                }
                ModelState.AddModelError("", result.Messages[0]);
            }
            return RedirectToAction("ReadTopic", new { Id = viewModel.TopicDeleteViewModel.TopicId });
        }

        [HttpPost("delete-topic")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTopic(TopicViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await topicService.DeleteTopicAsync(viewModel.TopicDeleteViewModel);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", result.Messages[0]);
            }
            return RedirectToAction("ReadTopic", new { Id = viewModel.TopicDeleteViewModel.TopicId });
        }

        [HttpGet("toggle-topic-bookmarks/{id?}")]
        public async Task<IActionResult> ToggleTopicBookmarks(int? id)
        {
            if (id == null)
            {
                return Json(false);
            }
            Result result = await bookmarkService.ToggleTopicBookmarksAsync(id.Value);
            if (result.Succeeded)
            {
                return Json(true);
            }
            return Json(false);
        }

        [AllowAnonymous]
        [HttpGet("topics/{username?}")]
        public async Task<IActionResult> Topics(string username)
        {
            MyTopicsAggregateViewModel viewModel = await topicViewModelService.GetUserTopics(username);

            if (viewModel.TopicIndexViewModels == null)
            {
                return View("PageNotFound");
            }

            return View(viewModel);
        }
    }
}

Presentation/Controllers/UserController.cs
using ApplicationCore.ViewModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.Interfaces;
using ApplicationCore.Helpers;
using ApplicationCore.ViewModels.Common;
using Microsoft.Extensions.Primitives;
using Microsoft.AspNetCore.Authentication;
using Newtonsoft.Json;

namespace Presentation.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly ICommonViewModelService commonViewModelService;
        private readonly IUserViewModelService userViewModelService;
        private readonly ICommonService commonService;

        public UserController(IUserService userService,
                              ICommonViewModelService commonViewModelService,
                              IUserViewModelService userViewModelService,
                              ICommonService commonService)
        {
            this.userService = userService;
            this.commonViewModelService = commonViewModelService;
            this.userViewModelService = userViewModelService;
            this.commonService = commonService;
        }

        [AllowAnonymous]
        [HttpPost("login-user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([FromBody]UserLoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await userService.LoginAsync(viewModel);
                return Json(result.Messages);
            }
            return Json("Wrong username or password.");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await userService.LogoutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Signup([FromBody]UserSignupViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await userService.SignupAsync(viewModel);
                return Json(result.Messages);
            }
            return Json(commonService.GetJsonModelStateError(ModelState));
        }

        [AllowAnonymous]
        [HttpGet("confirm-user-email", Name = "confirm-user-email")]
        public async Task<IActionResult> ConfirmEmail(string username, bool rememberMe, string token)
        {
            if (username == null || token == null)
            {
                ViewBag.ErrorTitle = "Error";
                ViewBag.ErrorMessage = "Confirmation failed. Please try again.";
                return View("Error");
            }

            Result result = await userService.ConfirmedSignupAsync(username, rememberMe, token);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ErrorViewModel viewModel = commonViewModelService.GetErrorViewModel(result);
                return View("Error", viewModel);
            }
        }

        [AcceptVerbs("Get")]
        [AllowAnonymous]
        [Route("check-username")]
        public async Task<IActionResult> IsUsernameTaken(string username)
        {
            if (username == null)
            {
                return Json(false);
            }
            bool taken = await userService.IsUsernameTakenAsync(username);

            if (taken)
            {
                return Json(false);
            }
            else
            {
                return Json(true);
            }
        }

        [AcceptVerbs("Get")]
        [AllowAnonymous]
        [Route("check-email")]
        public async Task<IActionResult> IsEmailTaken(string email)
        {
            if (email == null)
            {
                return Json(false);
            }
            bool taken = await userService.IsEmailTakenAsync(email);

            if (taken)
            {
                return Json(false);
            }
            else
            {
                return Json(true);
            }
        }

        [AllowAnonymous]
        [HttpGet("reset-password")]
        public IActionResult PasswordReset()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpGet("reset-password-email")]
        public async Task<IActionResult> SendResetPasswordEmail(string email)
        {
            await userService.SendResetVerificationCodeAsync(email);

            return Json(true);
        }

        [AllowAnonymous]
        [HttpGet("reset-password-code")]
        public async Task<IActionResult> ConfirmResetPasswordVerificationCode(int code)
        {
            await userService.ConfirmResetVerificationCodeAsync(code);

            return Json(true);
        }

        [HttpGet("my-profile/{username?}")]
        [Authorize(Roles = "User, Admin")]
        public async Task<IActionResult> MyProfile(string username)
        {
            UserProfileViewModel viewModel = await userViewModelService.GetUserEditProfileViewModelAsync(username);

            if (viewModel == null)
            {
                return RedirectToAction("PageNotFound", "Home");
            }
            bool userHasPermission = userService.UserHasPermission(username);

            if (userHasPermission)
            {
                return View(viewModel);
            }
            return RedirectToAction("AccessDenied", "Home");
        }

        [HttpPost("external-login")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl)
        {
            object properties = userService.GetExternalAuthenticationProperties(provider, returnUrl);
            return new ChallengeResult(provider, (AuthenticationProperties)properties);
        }

        [AllowAnonymous]
        [HttpGet("external-login-callback")]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ViewBag.ErrorTitle = "Error.";
                ViewBag.ErrorMessage = $"Error from external provider: {remoteError}";
                return View("Error");
            }

            Result result = await userService.ExternalLoginOrCreateUserAsync(returnUrl);

            if (!result.Succeeded)
            {
                ViewBag.ErrorTitle = "Error.";
                ViewBag.ErrorMessage = result.Messages[0];
                return View("Error");
            }
            return LocalRedirect(result.ReturnUrl);
        }

        [HttpPost("my-profile-change-username")]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUsername([FromBody]UserChangeUsernameViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await userService.EditUsernameAsync(viewModel);
                return Json(result.Messages);
            }
            return Json(commonService.GetJsonModelStateError(ModelState));
        }

        [HttpPost("my-profile-change-email")]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditEmail([FromBody]UserChangeEmailViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await userService.EditEmailAsync(viewModel);
                return Json(result.Messages);
            }
            return Json(commonService.GetJsonModelStateError(ModelState));
        }

        [HttpPost("my-profile-change-password")]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPassword([FromBody]UserChangePasswordViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Result result = await userService.EditPasswordAsync(viewModel);
                return Json(result.Messages);
            }
            return Json(commonService.GetJsonModelStateError(ModelState));
        }

        [HttpPost("my-profile-delete")]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteProfile([FromBody]UserDeleteProfileViewModel viewModel)
        {
            if (viewModel != null)
            {
                Result result = await userService.DeleteProfileAsync(viewModel);
                return Json(result.Messages);
            }
            return Json(commonService.GetJsonError("Error occured. Please try again."));
        }

        [HttpPost("my-profile-new-photo")]
        [Authorize(Roles = "User, Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadNewPhoto([FromBody]UserChangePhotoViewModel viewModel)
        {
            if (viewModel != null && viewModel.Base64.Contains("image"))
            {
                Result result = await userService.UploadProfilePhotoAsync(viewModel);
                return Json(result.Messages);
            }
            return Json(commonService.GetJsonError("Error occured. Please try again."));
        }

        [HttpGet("all-users")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AllUsers()
        {
            return View(await userService.GetAllUsersAsync());
        }

        [HttpPost("delete-user")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteUser(int id)
        {
            await userService.DeleteUserAsync(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

Presentation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h5>About</h5>
<p>Messaging board CRUD app developed using ASP.NET Core framework, Entity framework Core, SignalR, JavaScript and JQuery.</p>
<br />
<h6>Implemented features:</h6>
<ul style="list-style:outside; padding-left:20px">
    <li>    CRUD operations for users, topics and replies</li>
    <li>    User roles and logins - internal and external</li>
    <li>    Email sending for new profile confirmation and password reset</li>
    <li>    Background service for deleting uncorfimed users</li>
    <li>    Topic bookmarking</li>
    <li>    Notifications</li>
    <li>    Searching and sorting</li>
    <li>    Pagination</li>
    <li>    Profile image uploading</li>
</ul>
<br />
<p>Source code can be found <a href="https://bitbucket.org/MilutinB/clicktopic/src/master/" target="blank">here</a>.</p>
<hr />
<i>ClickTopic is a portfolio pet project not intended for commercial use.</i>

Presentation/Views/Home/AccessDenied.cshtml
@{
    ViewBag.Title = "Access Denied";
}

    <h4 class="text-danger">Access denied.</h4>
<h5 class="text-danger">You are not authorized to access this page.</h5>

Presentation/Views/Home/Index.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> signInManager
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> userManager
@model ApplicationCore.ViewModels.Topic.TopicIndexAggregateViewModel

@{
    ViewBag.Title = "Home Page";

    Dictionary<string, string> classes = new Dictionary<string, string>
    {
        ["Social"] = "bg-348aa7",
        ["Video"] = "bg-4436f8",
        ["Travel"] = "bg-5dd39e",
        ["Arts"] = "bg-ff755a",
        ["Tech"] = "bg-bce784",
        ["Gaming"] = "bg-83253f",
        ["Science"] = "bg-c49bbb",
        ["Exchange"] = "bg-3ebafa",
        ["Pets"] = "bg-c6b38e",
        ["Entertainment"] = "bg-a7cdbd",
        ["Education"] = "bg-525252",
        ["Q&As"] = "bg-777da7",
        ["Politics"] = "bg-368f8b",
        ["Hobbies"] = "bg-f9bc64"
    };
}

    <div class="">
        @{

            if (Model.SearchTerm != null)
            {
                <h5 style="font-weight:400;margin-top:20px">Search result for: <b>'@Model.SearchTerm'</b></h5>
            }
            else
            {
                string selectedCategory = Model.SelectedCategory ?? "All Categories";
                string selectedOrder = Model.OrderBy ?? "Latest";
                string latestActive = "active";
                string topActive = "";
                string followActive = "";
                if (Model.OrderBy == "Top")
                {
                    topActive = "active";
                    latestActive = "";
                    followActive = "";
                }
                if (Model.OrderBy == "Latest")
                {
                    latestActive = "active";
                    topActive = "";
                    followActive = "";
                }
                if (Model.OrderBy == "Follow")
                {
                    followActive = "active";
                    latestActive = "";
                    topActive = "";
                }
                <div class="nav">
                    <div class="nav__categories js-dropdown">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <div class="header__user-btn">
                                <a asp-controller="Topic" asp-action="CreateNewTopic"><img src=@Url.Content("~/pictures/New_Topic.svg") /></a>
                            </div>
                        }
                        <div class="nav__select">
                            <div class="btn-select dropdown__btn--open" data-dropdown-btn="categories">@selectedCategory</div>
                            <nav class="dropdown dropdown--design-01" data-dropdown-list="categories" style="">
                                <ul class="dropdown__catalog row">
                                    @foreach (var category in Model.Categories)
                                    {
                                        <li class="col-xs-6">
                                            <a asp-controller="Home" asp-action="Index" asp-route-category="@category" asp-route-order="@selectedOrder" class="category">
                                                <i class=@classes[category]></i>@category
                                            </a>
                                        </li>
                                    }
                                    <li class="col-xs-12 text-center" style="margin-top:5px; margin-bottom:-5px;">
                                        <a asp-controller="Home" asp-action="Index" asp-route-category="@null" asp-route-order="@selectedOrder" class="category">
                                            All Categories
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="nav__menu js-dropdown">
                        <ul>
                            <li class="@latestActive" id="latest"><a asp-controller="Home" asp-action="Index" asp-route-category="@Model.SelectedCategory" asp-route-order="Latest">Latest</a></li>
                            <li class="@topActive" id="top"><a asp-controller="Home" asp-action="Index" asp-route-category="@Model.SelectedCategory" asp-route-order="Top">Top Active</a></li>
                            @if (signInManager.IsSignedIn(User))
                            {
                                <li class="@followActive"><a asp-controller="Home" asp-action="Index" asp-route-order="Follow">Follow Feed</a></li>
                            }
                            @if (signInManager.IsSignedIn(User))
                            {
                                ApplicationUser user = await userManager.FindByNameAsync(User.Identity.Name);
                                if (user != null && await signInManager.UserManager.IsInRoleAsync(user, "Admin"))
                                {
                                    <li><a asp-controller="User" asp-action="AllUsers">All Users</a></li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            }
        }
        <div class="posts">
            <div class="posts__head">
                <div class="posts__topic">Topic</div>
                <div class="posts__category">Category</div>
                <div class="posts__users">Users</div>
                <div class="posts__replies">Replies</div>
                <div class="posts__views">Views</div>
                <div class="posts__activity">Activity</div>
            </div>
            <div class="posts__body">
                @if (Model.Page == 1 && !Model.UserClosedWelcome)
                {
                    <div class="posts__item bg-fef2e0" id="welcomeMessage">
                        <div class="posts__section-left">
                            <div class="posts__topic">
                                <div class="posts__content">
                                    <a asp-controller="Home" asp-action="Welcome">
                                        <h3>Welcome New Users! Please read this before posting!</h3>
                                    </a>
                                    <p>
                                        Congratulations, you have found the Community! Before you make a new topic or post, please read community guidelines.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <a asp-controller="Home" asp-action="SetWelcomeCookie" class="close-welcome"><i class="fal fa-window-close"></i></a>
                    </div>
                }
                @{
                    if (Model.TopicIndexViewModels.Count > 0)
                    {
                        for (int i = 0; i < Model.TopicIndexViewModels.Count; i++)
                        {
                            string bgColor = "";
                            if (i % 2 == 1) { bgColor = "bg-f2f4f6"; }

                            <div class="posts__item @bgColor">
                                <div class="posts__section-left">
                                    <div class="posts__topic">
                                        <div class="posts__content" style="">
                                            <a asp-controller="Topic" asp-action="ReadTopic" asp-route-id="@Model.TopicIndexViewModels[i].Id">
                                                <h3>@Model.TopicIndexViewModels[i].Title</h3>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="posts__category"><a class="category"><i class="@classes[Model.TopicIndexViewModels[i].Category]"></i>@Model.TopicIndexViewModels[i].Category </a></div>
                                </div>
                                <div class="posts__section-right">
                                    <div class="posts__users js-dropdown">
                                        @{ int photoCount = 0; }
                                        @foreach (var userInfo in Model.TopicIndexViewModels[i].UserInfos)
                                        {
                                            if (photoCount == 4)
                                            {
                                                break;
                                            }
                                            <div>
                                                <a asp-controller="Topic" asp-action="Topics" asp-route-username="@userInfo.Username" 
                                                   title="@userInfo.Username" class="avatar">
                                                <img class="profile-img-tiny" style="margin-left:-2px" src=@Url.Content(userInfo.PhotoPath) alt="avatar"></a>
                                            </div>
                                            photoCount++;
                                        }
                                    </div>
                                    <div class="posts__replies">@Model.TopicIndexViewModels[i].ReplyCount</div>
                                    <div class="posts__views">@Model.TopicIndexViewModels[i].ViewCount</div>
                                    <div class="posts__activity">@Model.TopicIndexViewModels[i].LastActive</div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <h5>No results.</h5>
                    }
                }
            </div>
        </div>
        @{
            <div class="pagination-wrap">
                <div class="pagination">
                    @if (Model.TopicIndexViewModels.Count > 0 && Model.SearchTerm == null && Model.TotalPages > 1)
                    {
                        if (Model.Page > 1)
                        {
                            <a asp-controller="Home" asp-action="Index" asp-route-page="@(Model.Page - 1)" asp-route-category="@Model.SelectedCategory" asp-route-order="@Model.OrderBy"><i class="fal fa-arrow-alt-left"></i></a>
                        }
                        if (Model.Page < 6 || Model.TotalPages < 10)
                        {
                            int max = Math.Min(9, Model.TotalPages);
                            for (int i = 0; i < max; i++)
                            {
                                string active = "";
                                if (i + 1 == Model.Page)
                                {
                                    active = "active";
                                }
                                <a asp-controller="Home" asp-action="Index" asp-route-page="@(i + 1)" asp-route-category="@Model.SelectedCategory" asp-route-order="@Model.OrderBy" class="@active">@(i + 1)</a>
                            }

                        }
                        else if (Model.TotalPages - Model.Page < 5)
                        {
                            for (int i = Model.TotalPages - 8; i <= Model.TotalPages; i++)
                            {
                                string active = "";
                                if (i == Model.Page)
                                {
                                    active = "active";
                                }
                                <a asp-controller="Home" asp-action="Index" asp-route-page="@i" asp-route-category="@Model.SelectedCategory" asp-route-order="@Model.OrderBy" class="@active">@i</a>
                            }
                        }
                        else
                        {
                            int[] pages = new int[9];

                            double firstDivisor = (double)(Model.Page - 1) / 4d;
                            double secondDivisor = (double)(Model.TotalPages - Model.Page) / 4d;
                            pages[0] = 1;
                            pages[1] = Model.Page - (int)Math.Floor(firstDivisor * 3d);
                            pages[2] = Model.Page - (int)Math.Floor(firstDivisor * 2d);
                            pages[3] = Model.Page - (int)Math.Floor(firstDivisor);
                            pages[4] = Model.Page;
                            pages[5] = Model.Page + (int)Math.Ceiling(secondDivisor);
                            pages[6] = Model.Page + (int)Math.Ceiling(secondDivisor * 2d);
                            pages[7] = Model.Page + (int)Math.Ceiling(secondDivisor * 3d);
                            pages[8] = Model.TotalPages;

                            for (int i = 0; i < pages.Length; i++)
                            {
                                string active = "";
                                if (pages[i] == Model.Page)
                                {
                                    active = "active";
                                }
                                <a asp-controller="Home" asp-action="Index" asp-route-page="@pages[i]" asp-route-category="@Model.SelectedCategory" asp-route-order="@Model.OrderBy" class="@active">@pages[i]</a>
                            }
                        }
                        if (Model.Page < Model.TotalPages)
                        {
                            <a asp-controller="Home" asp-action="Index" asp-route-page="@(Model.Page + 1)" asp-route-category="@Model.SelectedCategory" asp-route-order="@Model.OrderBy"><i class="fal fa-arrow-alt-right"></i></a>
                        }
                    }
                </div>
            </div>
        }
    </div>

<script src="~/js/index.js"></script>

Presentation/Views/Home/PageNotFound.cshtml
@{
    ViewBag.Title = "Page Not Found";
}

<h4 class="text-danger">Page not found.</h4>
<h5 class="text-danger">We couldn't find what you asked for.</h5>